export const STORE_NEWS = 'STORE_NEWS';
export const SHOW_SINGLE_POST = 'SHOW_SINGLE_POST';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
